package models

type Weapon struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Weight      string `json:"weight"`
	Price       string `json:"price"`
	Proficiency string `json:"proficiency"`
	WeaponClass string `json:"weaponClass"`
	DamageType  string `json:"damageType"`
	Source      string `json:"source"`
	Special     string `json:"special"`
	DmgT        string `json:"dmgT"`
	DmgS        string `json:"dmgS"`
	DmgM        string `json:"dmgM"`
	DmgL        string `json:"dmgL"`
	Critical    string `json:"critical"`
}

type Armor struct {
	Name               string `json:"name"`
	Description        string `json:"description"`
	Weight             string `json:"weight"`
	Price              string `json:"price"`
	Source             string `json:"source"`
	ArmorCheckPenalty  string `json:"armorCheckPenalty"`
	MaxDexBonus        string `json:"maxDexBonus"`
	ArcaneSpellFailure string `json:"arcaneSpellFailure"`
	ArmorType          string `json:"armorType"`
	ArmorBonus         string `json:"armorBonus"`
	Speed20Ft          string `json:"speed20Ft"`
	Speed30FFt         string `json:"speed30fFt"`
}

type Spell struct {
	Name                string `json:"name"`
	School              string `json:"school"`
	Subschool           string `json:"subschool"`
	Descriptor          string `json:"descriptor"`
	SpellLevel          string `json:"spell_level"`
	CastingTime         string `json:"casting_time"`
	Components          string `json:"components"`
	CostlyComponents    string `json:"costly_components"`
	Range               string `json:"range"`
	Area                string `json:"area"`
	Effect              string `json:"effect"`
	Targets             string `json:"targets"`
	Duration            string `json:"duration"`
	Dismissible         string `json:"dismissible"`
	Shapeable           string `json:"shapeable"`
	SavingThrow         string `json:"saving_throw"`
	SpellResistence     string `json:"spell_resistence"`
	Description         string `json:"description"`
	DescriptionFormated string `json:"description_formated"`
	Source              string `json:"source"`
	FullText            string `json:"full_text"`
	Verbal              string `json:"verbal"`
	Somatic             string `json:"somatic"`
	Material            string `json:"material"`
	Focus               string `json:"focus"`
	DivineFocus         string `json:"divine_focus"`
	Sor                 string `json:"sor"`
	Wiz                 string `json:"wiz"`
	Cleric              string `json:"cleric"`
	Druid               string `json:"druid"`
	Ranger              string `json:"ranger"`
	Bard                string `json:"bard"`
	Paladin             string `json:"paladin"`
	Alchemist           string `json:"alchemist"`
	Summoner            string `json:"summoner"`
	Witch               string `json:"witch"`
	Inquisitor          string `json:"inquisitor"`
	Oracle              string `json:"oracle"`
	Antipaladin         string `json:"antipaladin"`
	Magus               string `json:"magus"`
	Adept               string `json:"adept"`
	Deity               string `json:"deity"`
	SLALevel            string `json:"SLA_Level"`
	Domain              string `json:"domain"`
	ShortDescription    string `json:"short_description"`
	Acid                string `json:"acid"`
	Air                 string `json:"air"`
	Chaotic             string `json:"chaotic"`
	Cold                string `json:"cold"`
	Curse               string `json:"curse"`
	Darkness            string `json:"darkness"`
	Death               string `json:"death"`
	Disease             string `json:"disease"`
	Earth               string `json:"earth"`
	Electricity         string `json:"electricity"`
	Emotion             string `json:"emotion"`
	Evil                string `json:"evil"`
	Fear                string `json:"fear"`
	Fire                string `json:"fire"`
	Force               string `json:"force"`
	Good                string `json:"good"`
	LanguageDependent   string `json:"language_dependent"`
	Lawful              string `json:"lawful"`
	Light               string `json:"light"`
	MindAffecting       string `json:"mind_affecting"`
	Pain                string `json:"pain"`
	Poison              string `json:"poison"`
	Shadow              string `json:"shadow"`
	Sonic               string `json:"sonic"`
	Water               string `json:"water"`
	Linktext            string `json:"linktext"`
	ID                  string `json:"id"`
	MaterialCosts       string `json:"material_costs"`
	Bloodline           string `json:"bloodline"`
	Patron              string `json:"patron"`
	MythicText          string `json:"mythic_text"`
	Augmented           string `json:"augmented"`
	Mythic              string `json:"mythic"`
	Bloodrager          string `json:"bloodrager"`
	Shaman              string `json:"shaman"`
	Psychic             string `json:"psychic"`
	Medium              string `json:"medium"`
	Mesmerist           string `json:"mesmerist"`
	Occultist           string `json:"occultist"`
	Spiritualist        string `json:"spiritualist"`
	Skald               string `json:"skald"`
	Investigator        string `json:"investigator"`
	Hunter              string `json:"hunter"`
	HauntStatistics     string `json:"haunt_statistics"`
	Ruse                string `json:"ruse"`
	Draconic            string `json:"draconic"`
	Meditative          string `json:"meditative"`
	SummonerUnchained   string `json:"summoner_unchained"`
}

type CasterType struct {
	Class         string `json:"Class"`
	PrepareSpells string `json:"Prepare spells?"`
	Type          string `json:"Type"`
	AbilityScore  string `json:"Ability Score"`
	Field5        string `json:"field5"`
	Field6        string `json:"field6"`
	FullCaster    string `json:"Full caster"`
}

type Feat struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	Type              string `json:"type"`
	Description       string `json:"description"`
	Prerequisites     string `json:"prerequisites"`
	PrerequisiteFeats string `json:"prerequisite_feats"`
	Benefit           string `json:"benefit"`
	Normal            string `json:"normal"`
	Special           string `json:"special"`
	Source            string `json:"source"`
	Fulltext          string `json:"fulltext"`
	Teamwork          string `json:"teamwork"`
	Critical          string `json:"critical"`
	Grit              string `json:"grit"`
	Style             string `json:"style"`
	Performance       string `json:"performance"`
	Racial            string `json:"racial"`
	CompanionFamiliar string `json:"companion_familiar"`
	RaceName          string `json:"race_name"`
	Note              string `json:"note"`
	Goal              string `json:"goal"`
	CompletionBenefit string `json:"completion_benefit"`
	Multiples         string `json:"multiples"`
	SuggestedTraits   string `json:"suggested_traits"`
}

type MagicItem struct {
	Name              string `json:"Name"`
	Aura              string `json:"Aura"`
	Cl                string `json:"CL"`
	Slot              string `json:"Slot"`
	Price             string `json:"Price"`
	Weight            string `json:"Weight"`
	Description       string `json:"Description"`
	Requirements      string `json:"Requirements"`
	Cost              string `json:"Cost"`
	Group             string `json:"Group"`
	Source            string `json:"Source"`
	Al                string `json:"AL"`
	Int               string `json:"Int"`
	Wis               string `json:"Wis"`
	Cha               string `json:"Cha"`
	Ego               string `json:"Ego"`
	Communication     string `json:"Communication"`
	Senses            string `json:"Senses"`
	Powers            string `json:"Powers"`
	MagicItems        string `json:"MagicItems"`
	FullText          string `json:"FullText"`
	Destruction       string `json:"Destruction"`
	MinorArtifactFlag string `json:"MinorArtifactFlag"`
	MajorArtifactFlag string `json:"MajorArtifactFlag"`
	Abjuration        string `json:"Abjuration"`
	Conjuration       string `json:"Conjuration"`
	Divination        string `json:"Divination"`
	Enchantment       string `json:"Enchantment"`
	Evocation         string `json:"Evocation"`
	Necromancy        string `json:"Necromancy"`
	Transmutation     string `json:"Transmutation"`
	AuraStrength      string `json:"AuraStrength"`
	WeightValue       string `json:"WeightValue"`
	PriceValue        string `json:"PriceValue"`
	CostValue         string `json:"CostValue"`
	Languages         string `json:"Languages"`
	BaseItem          string `json:"BaseItem"`
	LinkText          string `json:"LinkText"`
	ID                string `json:"id"`
	Mythic            string `json:"Mythic"`
	LegendaryWeapon   string `json:"LegendaryWeapon"`
	Illusion          string `json:"Illusion"`
	Universal         string `json:"Universal"`
	Scaling           string `json:"Scaling"`
	IsIntelligentItem string `json:"IsIntelligentItem"`
}

type Monster struct {
	Name                       string `json:"Name"`
	Cr                         string `json:"CR"`
	Xp                         string `json:"XP"`
	Race                       string `json:"Race"`
	Class                      string `json:"Class"`
	MonsterSource              string `json:"MonsterSource"`
	Alignment                  string `json:"Alignment"`
	Size                       string `json:"Size"`
	Type                       string `json:"Type"`
	SubType                    string `json:"SubType"`
	Init                       string `json:"Init"`
	Senses                     string `json:"Senses"`
	Aura                       string `json:"Aura"`
	Ac                         string `json:"AC"`
	ACMods                     string `json:"AC_Mods"`
	Hp                         string `json:"HP"`
	Hd                         string `json:"HD"`
	HPMods                     string `json:"HP_Mods"`
	Saves                      string `json:"Saves"`
	Fort                       string `json:"Fort"`
	Ref                        string `json:"Ref"`
	Will                       string `json:"Will"`
	SaveMods                   string `json:"Save_Mods"`
	DefensiveAbilities         string `json:"DefensiveAbilities"`
	Dr                         string `json:"DR"`
	Immune                     string `json:"Immune"`
	Resist                     string `json:"Resist"`
	Sr                         string `json:"SR"`
	Weaknesses                 string `json:"Weaknesses"`
	Speed                      string `json:"Speed"`
	SpeedMod                   string `json:"Speed_Mod"`
	Melee                      string `json:"Melee"`
	Ranged                     string `json:"Ranged"`
	Space                      string `json:"Space"`
	Reach                      string `json:"Reach"`
	SpecialAttacks             string `json:"SpecialAttacks"`
	SpellLikeAbilities         string `json:"SpellLikeAbilities"`
	SpellsKnown                string `json:"SpellsKnown"`
	SpellsPrepared             string `json:"SpellsPrepared"`
	SpellDomains               string `json:"SpellDomains"`
	AbilityScores              string `json:"AbilityScores"`
	AbilityScoreMods           string `json:"AbilityScore_Mods"`
	BaseAtk                    string `json:"BaseAtk"`
	Cmb                        string `json:"CMB"`
	Cmd                        string `json:"CMD"`
	Feats                      string `json:"Feats"`
	Skills                     string `json:"Skills"`
	RacialMods                 string `json:"RacialMods"`
	Languages                  string `json:"Languages"`
	Sq                         string `json:"SQ"`
	Environment                string `json:"Environment"`
	Organization               string `json:"Organization"`
	Treasure                   string `json:"Treasure"`
	DescriptionVisual          string `json:"Description_Visual"`
	Group                      string `json:"Group"`
	Source                     string `json:"Source"`
	IsTemplate                 string `json:"IsTemplate"`
	SpecialAbilities           string `json:"SpecialAbilities"`
	Description                string `json:"Description"`
	FullText                   string `json:"FullText"`
	Gender                     string `json:"Gender"`
	Bloodline                  string `json:"Bloodline"`
	ProhibitedSchools          string `json:"ProhibitedSchools"`
	BeforeCombat               string `json:"BeforeCombat"`
	DuringCombat               string `json:"DuringCombat"`
	Morale                     string `json:"Morale"`
	Gear                       string `json:"Gear"`
	OtherGear                  string `json:"OtherGear"`
	Vulnerability              string `json:"Vulnerability"`
	Note                       string `json:"Note"`
	CharacterFlag              string `json:"CharacterFlag"`
	CompanionFlag              string `json:"CompanionFlag"`
	Fly                        string `json:"Fly"`
	Climb                      string `json:"Climb"`
	Burrow                     string `json:"Burrow"`
	Swim                       string `json:"Swim"`
	Land                       string `json:"Land"`
	TemplatesApplied           string `json:"TemplatesApplied"`
	OffenseNote                string `json:"OffenseNote"`
	BaseStatistics             string `json:"BaseStatistics"`
	ExtractsPrepared           string `json:"ExtractsPrepared"`
	AgeCategory                string `json:"AgeCategory"`
	Mystery                    string `json:"Mystery"`
	ClassArchetypes            string `json:"ClassArchetypes"`
	Patron                     string `json:"Patron"`
	CompanionFamiliarLink      string `json:"CompanionFamiliarLink"`
	FocusedSchool              string `json:"FocusedSchool"`
	Traits                     string `json:"Traits"`
	AlternateNameForm          string `json:"AlternateNameForm"`
	LinkText                   string `json:"LinkText"`
	ID                         string `json:"id"`
	UniqueMonster              string `json:"UniqueMonster"`
	ThassilonianSpecialization string `json:"ThassilonianSpecialization"`
	Variant                    string `json:"Variant"`
	Mr                         string `json:"MR"`
	Mythic                     string `json:"Mythic"`
	Mt                         string `json:"MT"`
	Spirit                     string `json:"Spirit"`
	PsychicMagic               string `json:"PsychicMagic"`
	KineticistWildTalents      string `json:"KineticistWildTalents"`
	Implements                 string `json:"Implements"`
	PsychicDiscipline          string `json:"PsychicDiscipline"`
}

type Race struct {
	ORIGINALORDER    string `json:"ORIGINAL ORDER"`
	Source           string `json:"SOURCE"`
	Race             string `json:"RACE"`
	Str              string `json:"STR"`
	Dex              string `json:"DEX"`
	Con              string `json:"CON"`
	Int              string `json:"INT"`
	Wis              string `json:"WIS"`
	Cha              string `json:"CHA"`
	Type             string `json:"TYPE"`
	Subtype          string `json:"SUBTYPE"`
	Size             string `json:"SIZE"`
	Rp               string `json:"RP"`
	OKForTonyEberron string `json:"OK for Tony - Eberron"`
}
